export enum PlayTypeEnum {
	TwoPtAttempt = '2-Pt Attempt',
	Block = 'Block',
	BlockedKick = 'Blocked Kick',
	FieldGoal = 'Field Goal',
	ForcedFumble = 'Forced Fumble',
	FumbleRecovery = 'Fumble Recovery',
	Interceotion = 'Interception',
	KickReturn = 'Kick Return',
	Pass = 'Pass',
	PassDefense = 'Pass Defense',
	PassDeflection = 'Pass Deflection',
	PlayerMelt = 'Player Melt',
	Pressure = 'Pressure',
	Punt = 'Punt',
	PuntReturn = 'Punt Return',
	Reception = 'Reception',
	Rush = 'Rush',
	Sack = 'Sack',
	Safety = 'Safety',
	StripSack = 'Strip Sack',
	Tackle = 'Tackle',
	TeamMelt = 'Team Melt'
}
